stages:
  - build
  - test
  - deploy


build_a:
  stage: build
  script:
    - echo "This job builds something."
     - mkdir build
    - touch build/info.txt
  artifacts:
    paths:
      - build/



test_a:
  stage: test
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "build stage are complete."
    - test -f "building/info.txt"
include:
  - template: Code-Quality.gitlab-ci.yml

deploy_a:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "test stage complete."
    - 'mvn deploy -s ci_settings.xml'
  only:
    - main
  
