stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    -echo "Building ..."
    -mkdir build
    -touch build/info.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    -echo "testing ..."
    -test -f "building/info.txt"

deploy:
  stage: deploy
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - main
